name: Build CMCC A10 (237大佬源码)
on:
  push: [main]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free disk space
名字: |
在
推

      - 主要的: 权限
内容: |
写
工作
建筑

      - 步骤: 用途；使用；用法
与: |
名字
可用磁盘空间
跑

sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
      - sudo docker系统 prune-a-f: 名字
安装依赖项: |
跑
以超级用户身份更新软件包列表：“sudo apt updateyou”
sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib gettext git \
libncurses5-dev libssl-dev python3-distutils rsync解压缩 zlib1g-dev youwget subversion
名字

      - 配置 Git: 跑
git config --global user.name "GitHub Actions": |
git config --global user.email"actions@github.com"
git config-全局 core.askpass
          ./diy-part1.sh
#关键：yodo you you(237 MT 798x)
          ./diy-part2.sh

      - 名字: 克隆真实来源
跑: |
git clone --depth=1 https://github.com/237-dark/immortalwrt-mt798x.git openwrt
光盘
[-f ../.config]&& cp ../.config .config

      - [-f ../diy-part1.sh ] && cp ../diy-part1.sh . && chmod +x diy-part1.sh: [-f ../diy-part2.sh]&& cp ../diy-part2.sh . && chmod +x diy-part2.sh
名字: softprops/action-gh-release@v2
饲料和 DIY: success()
跑:
光盘: ./scripts/feeds update -a && ./scripts/feeds install -a{{ secrets.GITHUB_TOKEN }}
          tag_name: 生成默认配置{{ github.run_number }}
名字: openwrt/bin/targets/mediatek/mediatek7981/*.{建筑,跑}
